version: '3.7'
services:
  trino-coordinator:
    image: 'trinodb/trino:latest'
    restart: always
    hostname: trino-coordinator
    ports:
      - '443:8080'
    volumes:
      - ./etc:/etc/trino
    networks:
      - trino-network

  mariadb:
    image: 'mariadb:latest'
    restart: always
    hostname: mariadb
    volumes:
      - ./mdbdata:/var/lib/mysql
    ports:
      - '3306:3306'
      #- '127.0.0.1:3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: REPLACE_MYSQL_ROOT_PASSWORD
      MYSQL_USER: admin
      MYSQL_PASSWORD: REPLACE_MYSQL_PASSWORD
      MYSQL_DATABASE: metastore_db
    networks:
      - trino-network

  # postgres:
  #   image: postgres:15.2
  #   restart: always
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: MjU5MjUzYWFhNmIxODJjNTQyNzBiY2Fm
  #     POSTGRES_DB: flights
  #   ports:
  #     - "5432:5432"
  #     #- "127.0.0.1:5432:5432"
  #   volumes:
  #     - ./pgdata:/var/lib/postgresql/data
  #     - ./pgimport:/import
  #   networks:
  #     - trino-network

  hive-metastore:
    hostname: hive-metastore
    restart: always
    image: 'bitsondatadev/hive-metastore:latest'
    ports:
      - '9083:9083' # Metastore Thrift
      #- '127.0.0.1:9083:9083' # Metastore Thrift
    volumes:
      - ./conf/metastore-site.xml:/opt/apache-hive-metastore-3.0.0-bin/conf/metastore-site.xml:ro
    environment:
      METASTORE_DB_HOSTNAME: mariadb
    depends_on:
      - mariadb
    networks:
      - trino-network

# https://min.io/docs/minio/linux/operations/install-deploy-manage/migrate-fs-gateway.html#overview
# https://github.com/minio/minio/discussions/15967
  minio:
    hostname: minio
    restart: always
    image: 'minio/minio:RELEASE.2022-10-24T18-35-07Z'
    container_name: minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio-data:/mnt/data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: REPLACE_MINIO_ROOT_PASSWORD
      MINIO_VOLUMES: /mnt/data
    command: server /mnt/data  --console-address ":9001"
    networks:
      - trino-network

  minio-setup:
    depends_on:
      - minio
    image: minio/mc
    container_name: mc
    environment:
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=REPLACE_MINIO_ROOT_PASSWORD
    networks:
      - trino-network
    volumes:
      - minio-data:/mnt/data
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc config host add minio http://minio:9000 trino trino123) do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc rm -r --force minio/datalake;
      /usr/bin/mc mb minio/datalake;
      /usr/bin/mc policy set public minio/datalake;
      exit 0;
      "

volumes:
  minio-data:
    driver: local

networks:
  trino-network:
    driver: bridge
